#!/bin/sh

# Source debconf library.
. /usr/share/debconf/confmodule

case "$1" in
    purge)
        # Remove all package's questions from debconf's database.
        db_purge
    ;;
    
    remove)
        # Stop services        
        systemctl daemon-reload
        systemctl stop openuem-console
        systemctl stop openuem-ocsp-responder
        systemctl stop openuem-nats
        systemctl stop openuem-agent-worker
        systemctl stop openuem-notification-worker
        systemctl stop openuem-cert-manager-worker
        systemctl stop openuem-server-updater
        systemctl daemon-reload

        # Remove user
        if getent passwd | grep -q '^openuem:'; then
            userdel openuem
        fi  
        
        # Remove config directory
        if [ -d /etc/openuem-server ]; then
            rm -rf /etc/openuem-server
        fi

        # Remove logs directory
        rm -rf /var/log/openuem-server

        # Remove services
        rm -rf /etc/systemd/system/openuem-*
        systemctl daemon-reload
        
        # Ref: https://thomas-leister.de/en/how-to-import-ca-root-certificate/
        certname="OpenUEM CA"
        ### For cert8 (legacy - DBM)
        for certDB in $(find /home -name "cert8.db")
        do
            certdir=$(dirname ${certDB});
            certutil -D -n "${certname}" -d dbm:${certdir}
            certutil -F -n "admin - OpenUEM" -d dbm:${certdir}
        done

        ### For cert9 (SQL)
        for certDB in $(find /home -name "cert9.db")
        do
            certdir=$(dirname ${certDB});
            certutil -D -n "${certname}" -d sql:${certdir}
            certutil -F -n "admin - OpenUEM" -d sql:${certdir}
        done

        # Remove /opt/openuem-server/bin
        rm -rf /opt/openuem-server/bin

        # Remove sudoers.d
        rm -rf /etc/sudoers.d/openuem
    ;;

    *)
        exit 0
    ;;
esac

exit 0